### ISSUE TITLE
Open hard dependency on azure-identity (or any other for that matter)

### ISSUE THREAD

**Issue by ivar-stange-4ss** [equinor/omnia-timeseries-python#37]
**Is your feature request related to a problem? Please describe.**
I'm using this library to communicate with Omnia, but I have the same dependencies w.r.t. to other tools using `azure-identity`. In `setup.py` the dependency is `azure-identity==1.10.0` which is pretty strict. I assume this is here either because a breaking change in a newer version broke the existing package implementation or that you needed the users to have at least this version.

This package may be used in a larger service and this requirement puts restrictions on other submodules of that service.

**Describe the solution you'd like**
Rewrite as `azure-identity>=1.10.0`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by o-fedorov** [comment]
Hi. I have created a PR for it: https://github.com/equinor/omnia-timeseries-python/pull/38
