### ISSUE TITLE
Issues when installing version 1.3.3

### ISSUE THREAD

**Issue by kjeel-dev** [equinor/omnia-timeseries-python#47]
I'm having the same issue with version 1.3.3 that was supposed to be solved in https://github.com/equinor/omnia-timeseries-python/issues/43

**Comment by janny93** [comment]
Hi,

Could you try again with newest version 1.3.5?

Best Regards,
Omnia Industrial IIoT team

**Comment by kjeel-dev** [comment]
Hi,

It works now, thank you!

BR.
Kjetil
